# Pray Votifier Config

# Welcome To Pray Votifier Config!
# This Is The Where You Can Config Everything In Pray Votifier!

# If You're Finding bStats Config Please Look Into
# plugins/bStats/config.yml

# This Is The Votifier Server Configurations
# Will Use Votifier Standard Protocol
votifier-server:
  # Votifier Server Port
  # This Is The Port That Votifier Server Will Listen To
  # Raw TCP Port Forward Is Needed
  port: 8192

  # The Address To Bind To
  host: "0.0.0.0"

# Here Is The Votifier Configurations
votifier:
  # Protocol Version Of Votifier
  # See https://mcstatus.io/tools/vote
  # In V1 (1) Will Use Only The key-file
  # In V2 (2) Will Use Only token
  # WARNING: V1 And V2 Are Talk In Different Packets!
  # If You See The Website Ask For Token This Will Be 2
  # If It Ask For Content In rsa/public.key This Will Be 1
  # Invalid Values Will Default To 2
  protocol-ver: 2

  # Save Method For Vote Data
  # This Is Used When Player Vote For This Server But The Player Is Not Online
  # You Can Choose Only file For Now The Database Method Is Not Implemented Yet!
  # Invalid Value Will Be Default To file
  save-method: "file"

  # Token (V2)
  # This Is Token For Votifier
  # Leave This Empty ("") Will Generate New Token When Server Start
  # This Don't Work If You Set protocol-ver To 1
  token: ""

  # Public Key File (V1)
  # This Is The Name Of The Key File We Save The Token On
  # You Can Manually Edit This File But Make Sure It Is Encoded In UTF-8!
  # This Don't Work If You Set protocol-ver To 2
  key-file: "rsa/public.key"

  # Command File
  # This Is The Name Of The Command File Include List Of Commands To Execute When Player Vote For This Server
  # Open The File And Add Your Commands In The File To Execute When Player Vote For This Server
  command-file: "commands.yml"

  # Timeout For Vote Request In Days
  # This Is When The Server Will Close The Vote Request
  # This Reduces The Size Of The Vote Request File If Players Just Vote With Random Username
  # This Is 1 Day By Default Because Votes Website Usually Reset Every Day
  # (In https://servers.eaglercraft.com/ For Example)
  # +1 Days Every 0:00 Of Your Server Time
  # 0 Or -1 To Disable
  timeout: 1

# ============================================================================
# This Is Coming Soon Configs And If You Change Settings Will Effect Nothing
# You Can View Them For Now But Change Them Will Effect Nothing
# ============================================================================

# Proxy Config
# This Is Required If Your Server Using Velocity With Our Velocity Version Of Plugin Installed
proxy:
  # If This Enabled The Built-In Web Server Will Be Disabled
  # And Let The Proxy Handle The Vote Request
  # Require The Proxy Plugin Installed On The Proxy Server
  demand-on-proxy: false

  # Do The Vote Data Save On Proxy Or Each Server Have Their Own Vote Data File?
  # This Will Ignored If You're Using Database Save Method
  # Or The Proxy Plugin Not Detected By The Server Plugin
  save-data-on-proxy: true

  # If This Enabled The Proxy Command That Included In The votifier.command-file
  # Example: /server some-server Or /glist all And Any Command That Only Exist On The Proxy
  # Will Be Forwarded To The Proxy To Execute The Command
  # Overwise The Plugin May Error With The Command Not Found On The Server
  # Don't Worry The Command That Exist On The Server Will Still Be Executed On The Server
  command-forward-to-proxy: true


# DON'T EVER THINK TO TOUCH THIS THING
# YOU WILL REGRET IT WHEN YOU REPLACE A PLUGIN JAR FILE WITH NEWER/OLDER VERSION
# SO PLEASE DON'T TOUCH THIS
# I'M BEGGING YOU
# PLEASE DON'T
# ACTUALLY YOU CAN TOUCH IT BUT DON'T OPEN ISSUES IF SOMETHING WENT WRONG
# WILL YOU STOP READING THIS?
# HELLO?
# NO NO SCROLL UP
# THIS IS NOT FOR YOU
# SCROLL UP NOW
# TRUST ME SCROLL UP
# YOU DON'T WANNA MEET A GOD IF YOU TOUCH THIS
# PLEASE I'M BEGGING YOU
# GO UP
# ...
# JUST SCROLL UP
# WHY YOU KEEP READING THIS
# JUST PLEASE
# ... Ok... Fine... I Will Stop Now...
# Are You Even Reading?
# Just Don't Touch It...
# Bye
# And Don't Scroll Down More...
cfg-ver: 1

# You Can Watch What cfg-ver Are Used For Here
# https://www.youtube.com/watch?v=dQw4w9WgXcQ